# Generated by Django 4.2.1 on 2023-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramordermessage',
            options={'verbose_name_plural': 'Телеграмм'},
        ),
    ]
