# Generated by Django 4.2.2 on 2023-06-16 10:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Точный адрес')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('telegram_name', models.CharField(max_length=50, verbose_name='Имя телеграм')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200, verbose_name='Название растения')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Старая цена')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Актуальная цена')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('main_img', models.ImageField(upload_to='images/%Y/%m', verbose_name='Главное фото растения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='PlantPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/%Y/%m', verbose_name='Галерея фотографий')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.plant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='plants',
            field=models.ManyToManyField(through='main.OrderItem', to='main.plant'),
        ),
    ]
