# Generated by Django 4.2.1 on 2023-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_plant_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Детали заказов'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name_plural': 'Растения'},
        ),
        migrations.AlterModelOptions(
            name='plantphotos',
            options={'verbose_name_plural': 'Галерея растений'},
        ),
    ]
